// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLiAyfzvDtivBHQJEAcyksXi4ttMhHGOU',
    appId: '1:88128136369:web:1fe1624fa3ea418b082e90',
    messagingSenderId: '88128136369',
    projectId: 'busconnect-cd7e2',
    authDomain: 'busconnect-cd7e2.firebaseapp.com',
    storageBucket: 'busconnect-cd7e2.firebasestorage.app',
    measurementId: 'G-F42B5CFEK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ1qqlX4rsYn6ftMPnIQ3KshSYkSXRiwUDFHTGRdg54',
    appId: '1:88128136369:android:aec696c237faf541082e90',
    messagingSenderId: '88128136369',
    projectId: 'busconnect-cd7e2',
    storageBucket: 'busconnect-cd7e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa0mEYKkPkYhgH2c0CSkaBaYGg5EdYpxE',
    appId: '1:88128136369:ios:36568d142a727542082e90',
    messagingSenderId: '88128136369',
    projectId: 'busconnect-cd7e2',
    storageBucket: 'busconnect-cd7e2.firebasestorage.app',
    iosBundleId: 'com.example.busConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa0mEYKkPkYhgH2c0CSkaBaYGg5EdYpxE',
    appId: '1:88128136369:ios:36568d142a727542082e90',
    messagingSenderId: '88128136369',
    projectId: 'busconnect-cd7e2',
    storageBucket: 'busconnect-cd7e2.firebasestorage.app',
    iosBundleId: 'com.example.busConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLiAyfzvDtivBHQJEAcyksXi4ttMhHGOU',
    appId: '1:88128136369:web:5afa870fbadfb3d8082e90',
    messagingSenderId: '88128136369',
    projectId: 'busconnect-cd7e2',
    authDomain: 'busconnect-cd7e2.firebaseapp.com',
    storageBucket: 'busconnect-cd7e2.firebasestorage.app',
    measurementId: 'G-7YKRXCPEGS',
  );
}
